# Taskfile.yml - RuleZ (AI Policy Engine) Project
#
# Task runner for building, testing, and managing RuleZ.
# Install Task: https://taskfile.dev/installation/
#
# Quick start:
#   task --list            # Show all available tasks
#   task build             # Build both CLI and UI
#   task test              # Run all unit tests
#   task test:all          # All tests including integration and E2E
#   task dev               # Start full dev environment
#   task ci                # Run full CI pipeline locally

version: '3'

# ===========================================================================
# Subproject Includes
# ===========================================================================

includes:
  cli:
    taskfile: ./rulez/Taskfile.yml
    dir: ./rulez
  ui:
    taskfile: ./rulez-ui/Taskfile.yml
    dir: ./rulez-ui

vars:
  PROJECT_NAME: rulez
  RULEZ_CLI_DIR: rulez
  INTEGRATION_DIR: test/integration
  RULEZ_BINARY: "{{.RULEZ_CLI_DIR}}/target/release/rulez"

tasks:
  # ===========================================================================
  # Core Development Tasks
  # ===========================================================================

  default:
    desc: Show available tasks
    cmds:
      - task --list

  build:
    desc: Build both CLI and UI
    cmds:
      - task: cli:build
      - task: ui:build

  build-cli:
    desc: Build RuleZ binary (release mode)
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo build --release
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/release/rulez

  build-debug:
    desc: Build RuleZ binary (debug mode)
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo build
    sources:
      - src/**/*.rs
      - Cargo.toml
    generates:
      - target/debug/rulez

  clean:
    desc: Remove build artifacts and test results
    cmds:
      - rm -rf {{.RULEZ_CLI_DIR}}/target
      - rm -rf {{.INTEGRATION_DIR}}/results/*.json
      - echo "Cleaned build artifacts and test results"

  # ===========================================================================
  # Testing Tasks
  # ===========================================================================

  test:
    desc: Run all Rust unit tests
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo test

  test-verbose:
    desc: Run Rust tests with verbose output
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo test -- --nocapture

  integration-test:
    desc: Run RuleZ + Claude CLI integration tests
    aliases: [itest]
    deps: [build]
    cmds:
      - ./{{.INTEGRATION_DIR}}/run-all.sh
    preconditions:
      - sh: command -v claude
        msg: "Claude CLI not found. Install it first."

  integration-test-quick:
    desc: Run quick integration tests (skip slow ones)
    aliases: [itest-quick]
    deps: [build]
    cmds:
      - ./{{.INTEGRATION_DIR}}/run-all.sh --quick

  integration-test-strict:
    desc: Run integration tests with strict mode (fail-fast on first assertion failure)
    aliases: [itest-strict]
    deps: [build]
    cmds:
      - ./{{.INTEGRATION_DIR}}/run-all.sh --strict

  integration-test-single:
    desc: Run a single integration test
    deps: [build]
    cmds:
      - ./{{.INTEGRATION_DIR}}/run-all.sh --test {{.TEST_NAME}}
    vars:
      TEST_NAME: '{{.TEST_NAME | default "01-block-force-push"}}'

  integration-test-single-strict:
    desc: Run a single integration test with strict mode
    deps: [build]
    cmds:
      - ./{{.INTEGRATION_DIR}}/run-all.sh --strict --test {{.TEST_NAME}}
    vars:
      TEST_NAME: '{{.TEST_NAME | default "01-block-force-push"}}'

  e2e:
    desc: Run CLI E2E integration tests
    deps: [build-cli]
    cmds:
      - ./e2e/run.sh
    preconditions:
      - sh: test -f e2e/run.sh
        msg: "E2E harness not found. Expected e2e/run.sh"

  test-all:
    desc: Run all tests (unit + integration + E2E)
    cmds:
      - task: test
      - task: ui:test
      - task: integration-test
      - task: ui:e2e

  # ===========================================================================
  # IQ/OQ/PQ Validation Tasks
  # ===========================================================================

  collect-iq:
    desc: Collect Installation Qualification evidence
    cmds:
      - ./scripts/collect-iq-evidence.sh --release

  collect-oq:
    desc: Collect Operational Qualification evidence
    cmds:
      - ./scripts/collect-oq-evidence.sh --release

  collect-pq:
    desc: Collect Performance Qualification evidence
    cmds:
      - ./scripts/collect-pq-evidence.sh --release

  collect-all:
    desc: Collect all IQ/OQ/PQ evidence
    cmds:
      - task: collect-iq
      - task: collect-oq
      - task: collect-pq
      - ./scripts/generate-validation-report.sh

  validation-report:
    desc: Generate combined validation report from existing evidence
    cmds:
      - ./scripts/generate-validation-report.sh

  coverage:
    desc: Generate test coverage report
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo tarpaulin --out Html --output-dir target/coverage
    status:
      - command -v cargo-tarpaulin

  # ===========================================================================
  # Code Quality Tasks
  # ===========================================================================

  lint:
    desc: Run clippy linter
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo clippy --all-targets --all-features -- -D warnings

  format:
    desc: Format code with rustfmt
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo fmt

  format-check:
    desc: Check code formatting without changes
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo fmt --check

  check:
    desc: Run all quality checks (format, lint, test)
    cmds:
      - task: format-check
      - task: lint
      - task: test

  # ===========================================================================
  # Installation Tasks
  # ===========================================================================

  install:
    desc: Install RuleZ globally via cargo
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo install --path .

  install-local:
    desc: Install RuleZ for current project
    deps: [build]
    cmds:
      - ./{{.RULEZ_BINARY}} install --binary ./{{.RULEZ_BINARY}}

  uninstall-local:
    desc: Uninstall RuleZ from current project
    deps: [build]
    cmds:
      - ./{{.RULEZ_BINARY}} uninstall

  # ===========================================================================
  # Development Utilities
  # ===========================================================================

  run:
    desc: Run RuleZ with arguments
    deps: [build-debug]
    cmds:
      - ./{{.RULEZ_CLI_DIR}}/target/debug/rulez {{.CLI_ARGS}}
    vars:
      CLI_ARGS: '{{.CLI_ARGS | default "--help"}}'

  debug:
    desc: Run RuleZ debug mode with test event
    deps: [build-debug]
    cmds:
      - ./{{.RULEZ_CLI_DIR}}/target/debug/rulez debug PreToolUse --tool Bash --command "echo test" --verbose

  repl:
    desc: Start RuleZ interactive REPL
    deps: [build-debug]
    cmds:
      - ./{{.RULEZ_CLI_DIR}}/target/debug/rulez repl

  logs:
    desc: Show recent RuleZ logs
    cmds:
      - "{{.RULEZ_BINARY}} logs --limit 20 2>/dev/null || tail -20 ~/.claude/logs/rulez.log"

  logs-tail:
    desc: Tail RuleZ logs in real-time
    cmds:
      - tail -f ~/.claude/logs/rulez.log

  validate:
    desc: Validate hooks.yaml configuration
    deps: [build]
    cmds:
      - ./{{.RULEZ_BINARY}} validate

  # ===========================================================================
  # Development Environment Tasks
  # ===========================================================================

  dev:
    desc: Start full dev environment (CLI watch + UI dev server)
    cmds:
      - echo "Starting development environment..."
      - echo "Run 'task cli:watch' in one terminal"
      - echo "Run 'task ui:dev' in another terminal"
      - task: ui:dev

  dev-cli:
    desc: Start CLI development with auto-rebuild
    cmds:
      - task: cli:watch

  dev-ui:
    desc: Start UI development server
    cmds:
      - task: ui:dev

  dev-ui-tauri:
    desc: Start Tauri desktop development
    cmds:
      - task: ui:dev:tauri

  run-app:
    desc: Run the RuleZ UI desktop app
    cmds:
      - lsof -ti:1420 | xargs kill -9 2>/dev/null || true
      - task: ui:dev:tauri

  # ===========================================================================
  # CI/CD Tasks
  # ===========================================================================

  ci:
    desc: Run full CI pipeline locally
    cmds:
      - task: clean
      - task: build-cli
      - task: check
      - task: test
      - echo "CI pipeline completed successfully"

  ci-full:
    desc: Run full CI pipeline including integration and E2E tests
    cmds:
      - task: ci
      - task: ui:check
      - task: ui:build
      - task: integration-test
      - task: ui:e2e

  # ===========================================================================
  # Documentation Tasks
  # ===========================================================================

  doc:
    desc: Generate Rust documentation
    dir: "{{.RULEZ_CLI_DIR}}"
    cmds:
      - cargo doc --no-deps --open

  # ===========================================================================
  # Release Tasks
  # ===========================================================================

  release-build:
    desc: Build release binary with optimizations
    dir: "{{.RULEZ_CLI_DIR}}"
    env:
      RUSTFLAGS: "-C target-cpu=native"
    cmds:
      - cargo build --release

  version:
    desc: Show RuleZ version
    deps: [build]
    cmds:
      - ./{{.RULEZ_BINARY}} --version
