//! Config file generation for runtime skill registries.
//!
//! After installing skills, updates the runtime's config file (GEMINI.md, AGENTS.md)
//! with a skill registry section bounded by markers. Preserves all non-skill content.

use std::fs;
use std::path::Path;

use anyhow::{Context, Result};

use crate::skills::discovery::SkillInventory;
use crate::skills::profiles::Runtime;

const MARKER_START: &str = "<!-- RULEZ_SKILLS_START -->";
const MARKER_END: &str = "<!-- RULEZ_SKILLS_END -->";

/// Generate a skill registry section for the given runtime.
fn generate_registry(inventory: &SkillInventory, runtime: &Runtime) -> String {
    let mut lines = vec![MARKER_START.to_string()];

    match runtime {
        Runtime::Gemini => {
            lines.push(String::new());
            lines.push(
                "<!-- Auto-generated by `rulez skills install`. Do not edit manually. -->"
                    .to_string(),
            );
            lines.push(String::new());
            for skill in &inventory.skills {
                lines.push("<skill>".to_string());
                lines.push(format!("<name>{}</name>", skill.name));

                // Extract description from SKILL.md frontmatter
                let desc = extract_description(&skill.entry_point).unwrap_or_default();
                if !desc.is_empty() {
                    lines.push(format!("<description>{desc}</description>"));
                }

                lines.push("</skill>".to_string());
                lines.push(String::new());
            }
        }
        Runtime::Codex | Runtime::OpenCode | Runtime::Custom(_) => {
            lines.push(String::new());
            lines.push(
                "<!-- Auto-generated by `rulez skills install`. Do not edit manually. -->"
                    .to_string(),
            );
            lines.push(String::new());
            lines.push("## Installed Skills".to_string());
            lines.push(String::new());
            lines.push("| Skill | Description |".to_string());
            lines.push("|-------|-------------|".to_string());

            for skill in &inventory.skills {
                let desc = extract_description(&skill.entry_point).unwrap_or_default();
                let short_desc = truncate_desc(&desc, 80);
                lines.push(format!("| {} | {} |", skill.name, short_desc));
            }

            lines.push(String::new());
        }
        Runtime::Claude => {
            // Claude doesn't need config gen — it's the canonical source
        }
    }

    lines.push(MARKER_END.to_string());
    lines.join("\n")
}

/// Extract the `description:` field from YAML frontmatter.
fn extract_description(skill_md: &Path) -> Option<String> {
    let content = fs::read_to_string(skill_md).ok()?;
    let trimmed = content.trim_start();
    if !trimmed.starts_with("---") {
        return None;
    }
    let rest = &trimmed[3..];
    let end = rest.find("\n---")?;
    let frontmatter = &rest[..end];

    for line in frontmatter.lines() {
        if let Some(desc) = line.strip_prefix("description:") {
            return Some(desc.trim().trim_matches('"').trim_matches('\'').to_string());
        }
    }
    None
}

/// Truncate a description to max length, adding "..." if needed.
fn truncate_desc(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        format!("{}...", &s[..max - 3])
    }
}

/// Update a config file with the skill registry section.
///
/// If markers already exist, replaces the content between them.
/// If no markers exist, appends the section at the end.
pub fn update_config_file(
    config_path: &Path,
    inventory: &SkillInventory,
    runtime: &Runtime,
) -> Result<bool> {
    if matches!(runtime, Runtime::Claude) {
        return Ok(false); // No config gen needed for Claude
    }

    let registry = generate_registry(inventory, runtime);

    if config_path.exists() {
        let content = fs::read_to_string(config_path)
            .with_context(|| format!("Failed to read {}", config_path.display()))?;

        let new_content = if content.contains(MARKER_START) && content.contains(MARKER_END) {
            // Replace existing section
            replace_between_markers(&content, &registry)
        } else {
            // Append to end
            format!("{}\n\n{}\n", content.trim_end(), registry)
        };

        fs::write(config_path, new_content)
            .with_context(|| format!("Failed to write {}", config_path.display()))?;
    } else {
        // Create new file with registry
        fs::write(config_path, format!("{registry}\n"))
            .with_context(|| format!("Failed to create {}", config_path.display()))?;
    }

    Ok(true)
}

/// Replace content between markers, preserving everything before start and after end.
fn replace_between_markers(content: &str, replacement: &str) -> String {
    let start_idx = content.find(MARKER_START).unwrap();
    let end_idx = content.find(MARKER_END).unwrap() + MARKER_END.len();

    let before = &content[..start_idx];
    let after = &content[end_idx..];

    format!("{before}{replacement}{after}")
}

/// Get the config file path for a runtime.
pub fn config_file_path(runtime: &Runtime, project_root: &Path) -> Option<std::path::PathBuf> {
    match runtime {
        Runtime::Gemini => Some(project_root.join("GEMINI.md")),
        Runtime::Codex | Runtime::OpenCode => Some(project_root.join("AGENTS.md")),
        Runtime::Claude | Runtime::Custom(_) => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::skills::discovery::SkillInventory;

    fn make_inventory(tmp: &tempfile::TempDir) -> SkillInventory {
        let skills_dir = tmp.path().join("skills");
        std::fs::create_dir_all(skills_dir.join("my-skill")).unwrap();
        std::fs::write(
            skills_dir.join("my-skill/SKILL.md"),
            "---\nname: my-skill\ndescription: A test skill for testing\n---\n# Content",
        )
        .unwrap();

        std::fs::create_dir_all(skills_dir.join("another-skill")).unwrap();
        std::fs::write(
            skills_dir.join("another-skill/SKILL.md"),
            "---\nname: another-skill\ndescription: Another great skill\n---\n# More",
        )
        .unwrap();

        SkillInventory::discover(&skills_dir, None, &[])
    }

    #[test]
    fn test_generate_gemini_registry() {
        let tmp = tempfile::tempdir().unwrap();
        let inventory = make_inventory(&tmp);
        let registry = generate_registry(&inventory, &Runtime::Gemini);

        assert!(registry.contains(MARKER_START));
        assert!(registry.contains(MARKER_END));
        assert!(registry.contains("<skill>"));
        assert!(registry.contains("<name>another-skill</name>"));
        assert!(registry.contains("<name>my-skill</name>"));
        assert!(registry.contains("<description>A test skill for testing</description>"));
    }

    #[test]
    fn test_generate_codex_registry() {
        let tmp = tempfile::tempdir().unwrap();
        let inventory = make_inventory(&tmp);
        let registry = generate_registry(&inventory, &Runtime::Codex);

        assert!(registry.contains("## Installed Skills"));
        assert!(registry.contains("| another-skill |"));
        assert!(registry.contains("| my-skill |"));
    }

    #[test]
    fn test_update_config_append() {
        let tmp = tempfile::tempdir().unwrap();
        let config = tmp.path().join("GEMINI.md");
        std::fs::write(&config, "# GEMINI Config\n\nSome existing content.\n").unwrap();

        let inventory = make_inventory(&tmp);
        let updated = update_config_file(&config, &inventory, &Runtime::Gemini).unwrap();
        assert!(updated);

        let content = std::fs::read_to_string(&config).unwrap();
        assert!(content.contains("Some existing content."));
        assert!(content.contains(MARKER_START));
        assert!(content.contains("<name>my-skill</name>"));
    }

    #[test]
    fn test_update_config_replace() {
        let tmp = tempfile::tempdir().unwrap();
        let config = tmp.path().join("AGENTS.md");
        let initial = format!(
            "# AGENTS Config\n\n{}\nOld skill registry\n{}\n\nFooter content.\n",
            MARKER_START, MARKER_END
        );
        std::fs::write(&config, &initial).unwrap();

        let inventory = make_inventory(&tmp);
        let updated = update_config_file(&config, &inventory, &Runtime::Codex).unwrap();
        assert!(updated);

        let content = std::fs::read_to_string(&config).unwrap();
        assert!(content.contains("# AGENTS Config"));
        assert!(content.contains("Footer content."));
        assert!(!content.contains("Old skill registry"));
        assert!(content.contains("| my-skill |"));
    }

    #[test]
    fn test_update_config_create_new() {
        let tmp = tempfile::tempdir().unwrap();
        let config = tmp.path().join("NEW_AGENTS.md");

        let inventory = make_inventory(&tmp);
        let updated = update_config_file(&config, &inventory, &Runtime::Codex).unwrap();
        assert!(updated);

        let content = std::fs::read_to_string(&config).unwrap();
        assert!(content.contains(MARKER_START));
        assert!(content.contains("| my-skill |"));
    }

    #[test]
    fn test_no_config_for_claude() {
        let tmp = tempfile::tempdir().unwrap();
        let config = tmp.path().join("CLAUDE.md");
        let inventory = make_inventory(&tmp);
        let updated = update_config_file(&config, &inventory, &Runtime::Claude).unwrap();
        assert!(!updated);
    }

    #[test]
    fn test_extract_description() {
        let tmp = tempfile::tempdir().unwrap();
        let skill_md = tmp.path().join("SKILL.md");
        std::fs::write(
            &skill_md,
            "---\nname: test\ndescription: My awesome description\n---\nBody",
        )
        .unwrap();
        assert_eq!(
            extract_description(&skill_md),
            Some("My awesome description".to_string())
        );
    }

    #[test]
    fn test_idempotent_update() {
        let tmp = tempfile::tempdir().unwrap();
        let config = tmp.path().join("GEMINI.md");
        std::fs::write(&config, "# Header\n").unwrap();

        let inventory = make_inventory(&tmp);

        // First update
        update_config_file(&config, &inventory, &Runtime::Gemini).unwrap();
        let first = std::fs::read_to_string(&config).unwrap();

        // Second update — should replace, not append
        update_config_file(&config, &inventory, &Runtime::Gemini).unwrap();
        let second = std::fs::read_to_string(&config).unwrap();

        // Count marker occurrences — should be exactly 1 each
        assert_eq!(
            second.matches(MARKER_START).count(),
            1,
            "Should have exactly one start marker"
        );
        assert_eq!(
            second.matches(MARKER_END).count(),
            1,
            "Should have exactly one end marker"
        );

        // Content should be stable after idempotent re-run
        assert_eq!(first, second);
    }
}
